# Postgres Only Compose

services:
  surge-postgres-standalone:
    image: postgres:15
    container_name: surge-postgres-standalone
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surge_development
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgres