### Health check
GET http://localhost:3000/health


### Sign up
POST http://localhost:3000/v1/sign_up/credentials
Content-Type: application/json

{
  "username": "testuser",
  "password": "secretpassword"
}

### Acquire Token
POST http://localhost:3000/v1/token?grant_type=credentials
Content-Type: application/json

{
  "username": "testuser",
  "password": "secretpassword"
}