// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package schema

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuthIdentity struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Data         json.RawMessage
	Provider     string
	ProviderID   string
	ProviderData json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
	LastSignIn   sql.NullTime
}

type AuthRefreshToken struct {
	ID        int64
	UserID    uuid.NullUUID
	Token     sql.NullString
	Revoked   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AuthUser struct {
	ID                uuid.UUID
	Email             sql.NullString
	Username          sql.NullString
	EncryptedPassword sql.NullString
	MetaAvatar        sql.NullString
	MetaFirstName     sql.NullString
	MetaLastName      sql.NullString
	MetaBirthdate     sql.NullTime
	MetaExtra         json.RawMessage
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastSignIn        sql.NullTime
}
